
# bazel build //:all
# ./bazel-bin/main
# bazel run @hedron_compile_commands//:refresh_all

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "//leet-good:0001-two-sum",
    ],
)
